/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/loginSuccess` | `/loginSuccess`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/verify` | `/verify`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/verifySuccess` | `/verifySuccess`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/attendance` | `/attendance`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/class` | `/class`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/teacher` | `/teacher`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/student` | `/student`; params?: Router.UnknownInputParams; } | { pathname: `/screens/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/student/[id]` | `/student/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/loginSuccess` | `/loginSuccess`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/verify` | `/verify`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/verifySuccess` | `/verifySuccess`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/attendance` | `/attendance`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/class` | `/class`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/teacher` | `/teacher`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/student` | `/student`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/student/[id]` | `/student/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/loginSuccess${`?${string}` | `#${string}` | ''}` | `/loginSuccess${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/verify${`?${string}` | `#${string}` | ''}` | `/verify${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/verifySuccess${`?${string}` | `#${string}` | ''}` | `/verifySuccess${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/attendance${`?${string}` | `#${string}` | ''}` | `/attendance${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/class${`?${string}` | `#${string}` | ''}` | `/class${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/teacher${`?${string}` | `#${string}` | ''}` | `/teacher${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/student${`?${string}` | `#${string}` | ''}` | `/student${`?${string}` | `#${string}` | ''}` | `/screens/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/loginSuccess` | `/loginSuccess`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/verify` | `/verify`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/verifySuccess` | `/verifySuccess`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/attendance` | `/attendance`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/class` | `/class`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/teacher` | `/teacher`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/student` | `/student`; params?: Router.UnknownInputParams; } | { pathname: `/screens/profile`; params?: Router.UnknownInputParams; } | `${'/(dashboard)'}/student/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/student/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(dashboard)'}/student/[id]` | `/student/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
